const TIPO_VALOR = {
    ENTERO: 'VAL_ENTERO',
    DECIMAL: 'VAL_DECIMAL',
    CADENA: 'VAL_CADENA',
    BOOL: 'VAL_BOLEANO',
    CHAR: 'VAL_CHAR',
    UNARIO:'VAL_UNARIO',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR'
}
module.exports = TIPO_VALOR;