const TIPO_DATO = {
    DECIMAL: 'DECIMAL',
    CADENA: 'CADENA',
    ENTERO: 'ENTERO',
    BOOL: 'BOOLEANO',
    CHAR: 'CHAR',
    LIST_DOUBLE:'LIST_DOUBLE',
    LIST_INT:'LIST_INT',
    LIST_BOOL:'LIST_BOOL',
    LIST_CHAR:'LIST_CHAR',
    LIST_CADENA:'LIST_CADENA'
}
module.exports= TIPO_DATO