const TIPO_INSTRUCCION = {
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    WHILE:'WHILE',
    DOWHILE:'DOWHILE',
    DEC_METODO:'DEC_METODO',
    EXEC: 'EXEC',
    LLAMADA_METODO:'LLAMADA_METODO',
    IF:'IF',
    IF_ELSE:"IF_ELSE",
    ELSE_IF:"ELSE_IF",
    IF_ELSE_IF:"IF_ELSE_IF",
    RETURN2:"RETURN2",
    DEC_FUNCION:"DEC_FUNCION",
    LISTA_VALORES:"LISTA_VALORES",
    MOD_LISTA:"MOD_LISTA",
    LISTA:"LISTA",
    LISTA_ANIADIR:"LISTA_ANIADIR",
    ACCESO_LIST:"ACCESO_LIST",
    RETURN1:"RETURN1"
}
module.exports = TIPO_INSTRUCCION